{% set version = '0.999-16' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-copula
  version: {{ version|replace("-", "_") }}

source:
  fn: copula_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/copula_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/copula/copula_{{ version }}.tar.gz
  sha256: 8a2b6c704701cba68fbdc837ca73db1f3d3c4bfbbdb2e4dab4d6af0c65b9d056

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-adgoftest
    - r-matrix
    - r-colorspace
    - r-gsl
    - r-lattice
    - r-mvtnorm
    - r-numderiv
    - r-pcapp
    - r-pspline
    - r-stabledist >=0.6_4
    - openblas

  run:
    - r-base
    - r-adgoftest
    - r-matrix
    - r-colorspace
    - r-gsl
    - r-lattice
    - r-mvtnorm
    - r-numderiv
    - r-pcapp
    - r-pspline
    - r-stabledist >=0.6_4
    - openblas

test:
  commands:
    - $R -e "library('copula')"  # [not win]
    - "\"%R%\" -e \"library('copula')\""  # [win]

about:
  home: http://copula.r-forge.r-project.org/
  license: GPL (>= 3) | file LICENCE
  summary: Classes (S4) of commonly used elliptical, Archimedean, extreme value and some more
    copula families.  Methods for density, distribution, random number generation, bivariate
    dependence measures, perspective and contour plots.  Fitting copula models including
    variance estimates.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
