# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NmDDq5Hv2nflwqKEigXBLWX6V/A2EViLtX1g8MShL6wFCWkcgkJU6JRGl3t+Op7bBr9YBE9uiqo9BEKvh1Yg8LTESgVqJ0l6pnc1yWXJuvn4vVgoWsFZ3qHX5WylIcRhkx43wLX5GnrsHifAyFGkIXPFXn8Mnta0AxzDQZPY+qveBkOO4wgoa6z41M1bC6cBH3P7tFSgeHPmurip6Q2v9jA5/b5ZEQZAa7AreEczBo5l5dH3gFT2WuGgXB0liqYPKsMDoBxmRWPI/QhwaFPygrcmfLnJpkvbcapxY2VrUHuHnwRM8UEcghgC20hxgRjERD+byqKTEuPtrMQQbAoZC+eEUUZi+LNeU2XLQSmqluJTqa6ki+FFVwjCmM7NVGiO/nqEVYsku/9mi5GlH6RWr+bKUSVrIhjwGwGotojoGXKfU5rVJChsWrNrs9+SKL83gzsOWtpP4QZUPfb1IwWnfE3P3ddUzcN8ceHcknwUH6olS1W8YDHGCymdR/BIALa7qhB3q8M6ThVSut8BjGIegABVbqukQeRHT6LMXc5TrPlTYLWvPYyEYKVOa8lX+WIVpGfO0O2gjOF5ddId4LXHKO4m1k5f31HmQnQPy12LhS0+w02ZoCxJSaF5r0snHxezPEKCc1CkswYzHgfzGJdDWUMzyEAnpcjnthWbZS+HbRY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
