appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NmDDq5Hv2nflwqKEigXBLWX6V/A2EViLtX1g8MShL6wFCWkcgkJU6JRGl3t+Op7bBr9YBE9uiqo9BEKvh1Yg8LTESgVqJ0l6pnc1yWXJuvn4vVgoWsFZ3qHX5WylIcRhkx43wLX5GnrsHifAyFGkIXPFXn8Mnta0AxzDQZPY+qveBkOO4wgoa6z41M1bC6cBH3P7tFSgeHPmurip6Q2v9jA5/b5ZEQZAa7AreEczBo5l5dH3gFT2WuGgXB0liqYPKsMDoBxmRWPI/QhwaFPygrcmfLnJpkvbcapxY2VrUHuHnwRM8UEcghgC20hxgRjERD+byqKTEuPtrMQQbAoZC+eEUUZi+LNeU2XLQSmqluJTqa6ki+FFVwjCmM7NVGiO/nqEVYsku/9mi5GlH6RWr+bKUSVrIhjwGwGotojoGXKfU5rVJChsWrNrs9+SKL83gzsOWtpP4QZUPfb1IwWnfE3P3ddUzcN8ceHcknwUH6olS1W8YDHGCymdR/BIALa7qhB3q8M6ThVSut8BjGIegABVbqukQeRHT6LMXc5TrPlTYLWvPYyEYKVOa8lX+WIVpGfO0O2gjOF5ddId4LXHKO4m1k5f31HmQnQPy12LhS0+w02ZoCxJSaF5r0snHxezPEKCc1CkswYzHgfzGJdDWUMzyEAnpcjnthWbZS+HbRY=
conda_forge_output_validation: true
